### ISSUE TITLE
Stolen bucket

### ISSUE THREAD

**Issue by smhutch** [sindresorhus/bucket-list#10]
![](http://i0.kym-cdn.com/photos/images/newsfeed/000/185/283/theybestealinmybucketseij5.jpg)

**Comment by msrose** [comment]
Pretty much required for any respectable bucket list 👍

**Comment by femoris** [comment]
Dont you dare to ... 
![aia5afk](https://user-images.githubusercontent.com/8181159/32134296-da344edc-bc07-11e7-95ef-a36493d6545c.jpg)

**Comment by sindresorhus** [comment]
Must have. Pull request please.

**Comment by fjoshuajr** [comment]
Submitted a PR here #31
