### ISSUE TITLE
Fire buckets

### ISSUE THREAD

**Issue by fjoshuajr** [sindresorhus/bucket-list#30]
<img src="https://4.imimg.com/data4/LI/GV/MY-2852330/fire-bucket-stand-500x500.jpg">

**DISCLAIMER**
<img src="https://cdn.shopify.com/s/files/1/0435/1925/products/Vintage-Fire-Bucket-Sign-Railway-GWR-Old_d9c12079-da45-4de8-bf1e-31124f9f36de_large.jpg?v=1492778100">

**Comment by sindresorhus** [comment]
Pull request welcome! ✨

**Comment by fjoshuajr** [comment]
Just submitted the PR on #47  :wink:

**Comment by vfonic** [comment]
I believe this issue is fixed and it can be closed. Is this project still being actively maintained? So many good projects are unmaintained these days...

**Comment by fjoshuajr** [comment]
Sorry, I forgot to close this one :smile:
